/** AUTO-GENERATED by scripts/scrape-module-videos.mjs */
export const MODULE_VIDEOS: Record<string, string[]> = {
  "analiz-relevantnosti": ["https://www.youtube.com/embed/Rjx-AZRsps4","https://www.youtube.com/embed/JRysfq-Nktk","https://www.youtube.com/embed/erbQpTwRKB0","https://www.youtube.com/embed/QSwQObGcIjM"],
  "monitoring-pozicii-sayta": ["https://www.youtube.com/embed/h_FdmZNWozA","https://www.youtube.com/embed/pIRlvwj78cw","https://www.youtube.com/embed/f8o7Mx9Oh5A","https://www.youtube.com/embed/_Wnn_Byvrs8"],
  "monitoring-saytov": ["https://www.youtube.com/embed/EHmnw0EIT1o"],
  "proverka-meta-tegov-online": ["https://www.youtube.com/embed/VzRp5vZ26Fc"],
  "podschet-dliny-teksta": ["https://www.youtube.com/embed/ouSX5Xsdk4M"],
  "sravnenie-spiskov-klyuchevykh-fraz": ["https://www.youtube.com/embed/aOHz0-25UAI"],
  "utm-metki": ["https://www.youtube.com/embed/dpScfE_Jqfg"],
  "kalkulyator-roi": ["https://www.youtube.com/embed/TVkoCRDaYJA"],
  "html-redaktor": ["https://www.youtube.com/embed/Af0XIPX520o"],
  "vydelenie-unikalnykh-slov-v-tekste": ["https://www.youtube.com/embed/IX9I6RajsEk"],
  "otslezhivanie-ssylok": ["https://www.youtube.com/embed/7kqQ3ftYEms"],
  "otslezhivanie-sroka-registratsii-domenov": ["https://www.youtube.com/embed/hvkBdJrMNIo"],
  "analiz-teksta": ["https://www.youtube.com/embed/H_wcnUFxHRw"],
  "klasterizator-klyuchevykh-slov": ["https://www.youtube.com/embed/MMLNuPH2ymA"],
};
