services:
  web:
    build: .
    ports:
      - "3001:3001"
    environment:
      PORT: "3001"
      NEXT_PUBLIC_LK_URL: https://lk.redbox.su
      LK_API_BASE_URL: https://lk.redbox.su
    restart: unless-stopped
